### ISSUE TITLE
Create a tree of geometry models

### ISSUE THREAD

**Issue by samehkamaleldin** [hci-lab/visualization-app#2]
Review the book of grammar of graphics then write down the list of geometry models in a form of a tree depending on inheritance relation between models.

**Comment by YusufMohamed** [comment]
https://github.com/hci-lab/visualization-app/blob/master/doc/Geometry.txt

Still modifying the file.

**Comment by samehkamaleldin** [comment]
please find geometry file update at  883090d1d97d90a105be42a6ea758c7c868dd572 and follow it to accomplish required set geometry models.

https://github.com/hci-lab/visualization-app/blob/883090d1d97d90a105be42a6ea758c7c868dd572/doc/geometry.md
